# from http://muelder.blogspot.fr/2015/08/building-eclipse-plugins-with-maven.html
sudo: false
language: java
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - MAVEN_OPTS="-Xmx2g"
jdk:
- oraclejdk8
before_install: echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc
script:
- mvn clean verify
# Prepare local dirs to deploy: copy repository
- chmod a+x prepare-deploy-local-dir.sh
- ./prepare-deploy-local-dir.sh $TRAVIS_BUILD_DIR/moliz.xmof.updatesites/updatesite/nightly
deploy:
  - provider: pages
    skip_cleanup: true
    github_token:   
      secure: cT2xFVUU6kCbJzSn+yXjPtxD7EMz6mq49vXUF5Op7fVvMkPqY5GqB/2hGFt4eD950+wRqSeAdcFj9NKeIE06KJXbGTSLn0VIjTQI9J3jSFeDyeefafOwTLW7vR7BVptJSHNuG8UpN53mf8rgPFrhmSu4BXXOSXQ5XZKcvmKtRLbtqdpHUQpNHHHSlEKG6/SeLXrbQVqul94BFVojYgrgIwa+l+LN+KzkTUFJj+ltrDqRkjqoJcySrOI3//Etrv+rqSHF4LBSzkfgTN/xis94WsOo9RaELP0+ir+xcujnXwO+q54dPZSYrELDv9SRssXUW0lmhjAfH8hy0Cj7deHRJP/N/TU6IYvjGBcP4ulmkW4f9rt5XqQDV6YmbiITOw1VWB/bxx5z8wx0FGMikOberCPtdxAAY54gWBMSupwE/vyO8kqzOkgz05g1+6W3m75aIr9hk7LjU4klKwtBg0JO+ROxu6pXskaIPlezuNcSlBTEOIo7HBvJKc4AzWBbT/7h12p7TuAjxp4VeOsahQb3Iqg5nmXe1Bzg6J/L5mvLxTk7aA21kUMq0fw7O2JA6A0VNZuOSL4lwztdFnJV+ICnr3MHxBrfCZl3EuY4ujx0E4C2hCLNKj9uEmfuqDrmRRWv8Jl8Ke6yQMz49jSyUmo9IHAqSSpH95nQsGoPfDeu890=  
    repo: moliz/moliz.xmof
    target_branch: gh-pages
    local-dir: "${TRAVIS_BUILD_DIR}/moliz.xmof.updatesites"
    on:
      branch: master
# copy the zip to github release on tags with the release pattern
  - provider: releases
    skip_cleanup: true
    api_key:   
      secure: cT2xFVUU6kCbJzSn+yXjPtxD7EMz6mq49vXUF5Op7fVvMkPqY5GqB/2hGFt4eD950+wRqSeAdcFj9NKeIE06KJXbGTSLn0VIjTQI9J3jSFeDyeefafOwTLW7vR7BVptJSHNuG8UpN53mf8rgPFrhmSu4BXXOSXQ5XZKcvmKtRLbtqdpHUQpNHHHSlEKG6/SeLXrbQVqul94BFVojYgrgIwa+l+LN+KzkTUFJj+ltrDqRkjqoJcySrOI3//Etrv+rqSHF4LBSzkfgTN/xis94WsOo9RaELP0+ir+xcujnXwO+q54dPZSYrELDv9SRssXUW0lmhjAfH8hy0Cj7deHRJP/N/TU6IYvjGBcP4ulmkW4f9rt5XqQDV6YmbiITOw1VWB/bxx5z8wx0FGMikOberCPtdxAAY54gWBMSupwE/vyO8kqzOkgz05g1+6W3m75aIr9hk7LjU4klKwtBg0JO+ROxu6pXskaIPlezuNcSlBTEOIo7HBvJKc4AzWBbT/7h12p7TuAjxp4VeOsahQb3Iqg5nmXe1Bzg6J/L5mvLxTk7aA21kUMq0fw7O2JA6A0VNZuOSL4lwztdFnJV+ICnr3MHxBrfCZl3EuY4ujx0E4C2hCLNKj9uEmfuqDrmRRWv8Jl8Ke6yQMz49jSyUmo9IHAqSSpH95nQsGoPfDeu890=    
    file_glob: true
    file: releng/org.modelexecution.moliz.xmof.updatesite/target/*.zip
    on:  
      tags: true
      condition: "$TRAVIS_TAG =~ ^release.*$"
