<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="event"
    nsURI="http://events/1.0" nsPrefix="event">
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionEvent" abstract="true" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" lowerBound="1"
        eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Action" instanceClassName="fUML.Syntax.Actions.BasicActions.Action"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Activity" instanceClassName="fUML.Syntax.Activities.IntermediateActivities.Activity"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Token" instanceClassName="fUML.Semantics.Activities.IntermediateActivities.Token"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ActivityNode" instanceClassName="fUML.Syntax.Activities.IntermediateActivities.ActivityNode"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ActivityEdge" instanceClassName="fUML.Syntax.Activities.IntermediateActivities.ActivityEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoActionStartEvent" eSuperTypes="#//ActionEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoActionEndEvent" eSuperTypes="#//ActionEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNodeEvent" abstract="true" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="node" lowerBound="1" eType="#//ActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FireEvent" eSuperTypes="#//ActivityNodeEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokens" upperBound="-1"
        eType="#//Token"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiveOfferEvent" eSuperTypes="#//ActivityNodeEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsReadyEvent" eSuperTypes="#//ActivityNodeEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReady" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SendOfferEvent" eSuperTypes="#//ActivityEdgeInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokens" upperBound="-1"
        eType="#//Token"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdgeInstance" abstract="true"
      eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edge" lowerBound="1" eType="#//ActivityEdge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEvent" abstract="true" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activity" lowerBound="1"
        eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityExectutionStartEvent" eSuperTypes="#//ActivityEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" upperBound="-1"
        eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityExecutionEndEvent" eSuperTypes="#//ActivityEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" upperBound="-1"
        eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Value" instanceClassName="fUML.Semantics.Classes.Kernel.Value"/>
</ecore:EPackage>
